#!/bin/bash
set +x
set -e
. .colors.sh
source /root/.bashrc
BASEDIR=$PWD
. $BASEDIR/io.sh 0 8 1 "$@"
CURDIR=`pwd`
## INPUTS VARIABLES


## PARAMETERS VARIABLES
gldas_dataset_id=${PARAMS1}
shapefile_dataset_id=${PARAMS2}
agg_function=${PARAMS3}
agg_time_period=${PARAMS4}
range_start_time=${PARAMS5}
range_end_time=${PARAMS6}
range_step_time=${PARAMS7}
csv_output_file=${PARAMS8}


set -xe

####### WRITE YOUR INVOCATION LINE AFTER THIS COMMENT


pushd .
/ws/run --config examples/dame/templates/average_daily_all_variables.yml.template -i2 "$shapefile_dataset_id" -i1 "$gldas_dataset_id" -p1 "$agg_function" -p2 "$agg_time_period" -p3 "$range_start_time" -p4 "$range_end_time" -p5 "$range_step_time" -o1 $csv_output_file
popd

set +x
echo -e "$(c G)[success] The model has exited with code SUCCESS"
####### WRITE YOUR INVOCATION LINE BEFORE THIS COMMENT
cd $BASEDIR
. $BASEDIR/output.sh
